### PR TITLE
Fixed broken github blame image

### LINKED ISSUE #215: Missing screenshot of Github Blame on the contribution wiki
Hi, i was going through the contribution wiki to setup the project and noticed that one of the screenshot link was broken. 

Link - https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#notes

Screenshot 2023-12-26 at 10 05 55 PM

Do let me know if can send a PR to add the image

### PR DESCRIPTION
**Pull request by jaiakash**
Hi i have added the image for GitHub blame image that was broken in the wiki.

Closes #215

### CODE REVIEW

**Comment by jaiakash** [comment]
One more thing, i was seeing other pages, all of them are broken which have images linked via ```images``` folder. (For eg [this](https://github.com/oppia/oppia/wiki/Tips-for-common-IDEs) and [this](https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages) )

I tried some other ways like ```img``` tag or using diffrent format, but i didnt work out.

Only images which are directly added by drag and drop are working. ( For eg 2nd point at [this](https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages#super-admin-page) )

**Comment by seanlip** [comment]
Just an FYI, I looked at the pages you linked to and the images load for me. What image URL specifically is not resolving for you?

**Comment by seanlip** [comment]
Also, please put the image in the images/ folder, not your fork.

**Comment by jaiakash** [comment]
I will explain in detail, in the oppia wiki, any images which are added direclty from ```image``` folder repo is broken. For eg, the page at #215 , [this page](https://github.com/oppia/oppia/wiki/Tips-for-common-IDEs) and [this page](https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages)

Attached screenshot
Screenshot 2023-12-26 at 10 05 55 PM
Screenshot 2023-12-28 at 12 34 30 AM


You can try loading any of above 3 pages, the page will load instantly but the browser will keep on loading and eventually fail to load the images, as shown in above screenshot.

When I digged down the source of these images, all of them were linked with ```images``` folder.
 The *first screenshot* is part of this page, https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#notes
 The *second* is part of this page, https://github.com/oppia/oppia/wiki/Tips-for-common-IDEs#atom

**Comment by jaiakash** [comment]
But the images which are added directly will show without any issue. 
Let me give you a example, open this page https://github.com/oppia/oppia/wiki/How-to-access-Oppia-webpages#super-admin-page

Screenshot 2023-12-28 at 12 29 52 AM

The code
Screenshot 2023-12-28 at 12 30 23 AM

Notice how the green one shows up (its directly added) but 2 red ones fails (since its added by ```images``` folder)
This was point I was trying to explain earlier. I hope I am clear in demonstrating the issue. Let me know how I can help.

**Comment by seanlip** [comment]
Thanks @jaiakash. The thing is, the images are loading for me:


Screenshot from 2023-12-29 18-32-15

So it's not clear to me whether the issue is with GitHub or if it's with your browser/machine. Could you please check whether it loads for other contributors or not, before we make this change? If you could get them to chime in on this thread, that would be great.

It might also be worth contacting GitHub Support because this seems like it may be a bug with their website.

Regardless of the issue, we cannot accept a PR that includes images from github.com/jaiakash because those images won't be under our control. It would be worth finding a different solution that's not tied to your own repo.

**Comment by jaiakash** [comment]
Hi @seanlip 
> Regardless of the issue, we cannot accept a PR that includes images from github.com/jaiakash because those images won't be under our control. It would be worth finding a different solution that's not tied to your own repo.

First thing first, I have updated the image and added the screenshot in ```images``` folder as suggested by you.

**Comment by seanlip** [comment]
@jaiakash I'm a bit confused, what was wrong with the original screenshot? Are you able to see the image on this page? https://github.com/oppia/oppia-web-developer-docs/blob/ee54c36d3c09f840b2ca5832c7eec50401cd6eab/images/githubBlame.png

**Comment by jaiakash** [comment]
2nd things, i agree its a bit strange but i did tried using incognito, different browser, and even different laptop. 
So issue seemed with my network, with my current network (Jio, a telecom operator in India), the github images are not working. I tried different network (Airtel), images are working fine. I literally have no explanation but yeah the problem seems to with my network.👀

**Comment by jaiakash** [comment]
Here is video proof: https://photos.app.goo.gl/qgT8GDdTP9Km462q8

**Comment by seanlip** [comment]
Thanks @jaiakash.

So what should we do here, do you think?  Is there anything that we should fix?

**Comment by jaiakash** [comment]
From code part, I feel the current image is working perfectly fine. So this PR is redundant.
But for network side. It really confusing why some of github domains are blocked on Jio.

Check this I found on other repos https://github.com/orgs/community/discussions/42655 Jio has blocked Github domains, there is even news article regarding that. 😅😂

**Comment by jaiakash** [comment]
Update: I fixed the issue by changing the DNS of my system to (8.8.8.8 or 1.1.1.1).

**Comment by seanlip** [comment]
Thanks @jaiakash! Do you think it's worth adding this fix to the wiki troubleshooting page? We can do that instead of this PR I think.

**Comment by jaiakash** [comment]
> Do you think it's worth adding this fix to the wiki troubleshooting page?

This is caused by external issue, but still many of users (specially who are using Jio network), will face this face, so in my opinion we can add a fix.

>We can do that instead of this PR I think.

Yeah I will add that in that PR.

**Comment by jaiakash** [comment]
Hi @seanlip should i add the fix info at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia page only or you want it to be added at any other page as well.

 The images might not shown in other pages, but I don't consider that as deal breaker as such. But if someone tries to install the dependencies, this same error pops up (It did for me when I tried setting up the project). So in my opinion, it makes more sense to add the fix in https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia page , since first-time contributors would be visiting that page initially.

**Comment by seanlip** [comment]
Hm, I was thinking maybe the troubleshooting page, which is where folks might go to if they have installation issues? If you add it directly to the main "contributing code" page then it becomes pretty long for new contributors.

**Comment by jaiakash** [comment]
Sure understood, will do it now.

**Comment by jaiakash** [comment]
Hi @seanlip please check #223

**Pull request closed without merging**
