### PR TITLE
Fix #92: Create .gitignore

### LINKED ISSUE #92: Add .gitignore file to wiki repo
I was reviewing https://github.com/oppia/oppia-web-developer-docs/pull/80/files and it looks like a .DS_Store file was mistakenly included with the PR.

Should we add a .gitignore to this repo so that such files are ignored, just like we do in the [Web repo](https://github.com/oppia/oppia/blob/develop/.gitignore)?

### PR DESCRIPTION
**Pull request by vedant-z**
Created .gitignore file for "[oppia-web-developer-docs](https://github.com/oppia/oppia-web-developer-docs)" repository and included necessary file to be ignored.

Will add more files if found necessary to add.

### CODE REVIEW

**Comment by vedant-z** [comment]
@seanlip Please review the changes.

**Comment by seanlip** [comment]
@vedant-z Please follow the steps [here](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up) to get started first (at least numbers 1 and 2), then reopen this PR. We can't merge your PR until you've done that. Thanks!

**Comment by seanlip** [comment]
This looks fine now, merging it. Thanks @vedant-z! 

In the future please read the instructions at https://github.com/oppia/oppia/wiki/Make-a-pull-request and follow the steps there, e.g. in terms of giving your PR a good title. That will prevent delays in merging. Thanks!

**Comment by vedant-z** [comment]
@seanlip Ya I will keep that in mind from next time.

Thanks

**Pull request merged**
