### PR TITLE
Fix #319 : Deprecated the Onboarding Mentor Program

### LINKED ISSUE #319: Deprecate the Onboarding Mentor Program.
Per the discussion with the welfare team, we are planning to deprecate the Onboarding Mentor Program as we don't have the bandwidth to assign mentors to all the folks and also most of the queries asked from mentees can be found in wiki or resolved via github discussions.

### PR DESCRIPTION
**Pull request by HardikGoyal2003**
Removed the onboarding mentor program and form link, mentioned in #319 .

### CODE REVIEW

**Comment by HardikGoyal2003** [comment]
@Ash-2k3 PTAL! Thanks!

**Review by Ash-2k3 — APPROVED** [review]
Thanks, LGTM! -- Just make sure that this link is not there in any other wiki pages :)

@HardikGoyal2003 Ping me when you have confirmed this so that we can merge this PR, thanks!

**Comment by HardikGoyal2003** [comment]
@Ash-2k3 I checked but couldn't find anything with `onboarding mentors` in the codebase so, I think we can merge this!

**Comment by Ash-2k3** [comment]
Thanks @HardikGoyal2003, merged this PR :)

**Pull request merged**
