### PR TITLE
docs: unify formatters and bytes and strings handling into Coding-style-guide.md

### PR DESCRIPTION
**Pull request by gutoslv**
Issue #337 

Folds Formatters.md and Bytes-and-string-handling-in-Python-3.md into Coding-style-guide.md

### CODE REVIEW

**Review by seanlip — CHANGES_REQUESTED** [review]
Thanks @gutoslv! This looks great, just a question, could you please update _Sidebar.md as well (to not point to the deleted files)?

Thanks!

**Comment by seanlip** [comment]
Also, please leave a comment on the original issue so that we can assign you to it. Thanks!

**Comment by gutoslv** [comment]
Hey @seanlip just removed the mention to the deleted links, and left a comment on the original issue. Please let me know if I need to change any other thing. Thanks in advance.

**Review by seanlip — APPROVED** [review]
Looks great. Thanks @gutoslv, and congrats on your first Oppia PR!

**Pull request merged**
