### PR TITLE
Fix some indentation errors on the "If your CI checks fail..." page.

### PR DESCRIPTION
**Pull request by seanlip**
Fix a few indentation errors on the "If your CI checks fail..." page, as well as a broken wiki redirect link.

### CODE REVIEW

**Comment by seanlip** [comment]
@HardikGoyal2003 PTAL. Thanks!

**Review by HardikGoyal2003 — COMMENTED** [review]
@seanlip Everything looks good, just one thing I noticed:
- I think this also needs to be fixed: `[trace which PR caused the error|How-to-find-the-commit-which-introduced-a-bug]`

**Comment by seanlip** [comment]
Thanks @HardikGoyal2003, I think you're right! I fixed it, PTAL, thanks.

**Comment by HardikGoyal2003** [comment]
@seanlip LGTM, Thanks!

**Pull request merged**
