### PR TITLE
Fix #308: Removed Events Page

### LINKED ISSUE #308: Depreciate Events Team
As the activities listed on the page are now inactive so, we are depreciating this page as discussed with the welfare team.
https://github.com/oppia/oppia/wiki/Events-Team

### PR DESCRIPTION
**Pull request by HardikGoyal2003**
#308 
- Removed Events Page
- Updated Sidebar

### CODE REVIEW

**Comment by HardikGoyal2003** [comment]
@Ash-2k3 PTAL! Thanks!

**Review by Ash-2k3 — APPROVED** [review]
Thanks, LGTM!

**Comment by Ash-2k3** [comment]
Assigning @seanlip for final review, Thanks!

**Review by seanlip — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
