### PR TITLE
Fix part of issue #210: Add info to the wiki about how to find the commit which caused an issue. 

### PR DESCRIPTION
**Pull request by satvshr**
Added[ my page](https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug) to the sidebar of the wiki.

### CODE REVIEW

**Review by seanlip — CHANGES_REQUESTED** [review]
@satvshr Please follow the PR guidelines -- make sure your title follows the usual instructions, and that the description is populated. Otherwise your PRs cannot be reviewed and will likely be closed for not following guidelines.

**Comment by satvshr** [comment]
@seanlip kindly check it out, also could you tell me if my work [here](https://github.com/oppia/oppia/issues/19297) counts as a solved issue because I want to apply for the "member" role which I remember requires 2 completed issues.

**Review by seanlip — CHANGES_REQUESTED** [review]
This PR should only add the new page to the wiki. Why does it contain all the other stuff? Please check your Files Changed tab and ensure that it contains only what is required.

> also could you tell me if my work https://github.com/oppia/oppia/issues/19297 counts as a solved issue because I want to apply for the "member" role which I remember requires 2 completed issues.

No, because the issue isn't solved/resolved yet. In any case, I think it is still a good idea for you to attempt other issues in order to gain familiarity with the codebase.

**Comment by satvshr** [comment]
> This PR should only add the new page to the wiki. Why does it contain all the other stuff? Please check your Files Changed tab and ensure that it contains only what is required.

It is doing exactly that sean, its adding the link to my page to debugging.md, adding the images required to assets, and adding the link to my page to sidebar

**Comment by seanlip** [comment]
@satvshr The Files Changed tab is supposed to show a **diff** with the current codebase. The current codebase already has the images you mentioned, so something seems to be wrong with this PR. Please figure out what that is and fix it. https://github.com/oppia/oppia-web-developer-docs/tree/develop/images/findCommitWhichIntroducedBug

**Comment by seanlip** [comment]
P.S. I suspect it might be because your remote repo is not up-to-date with develop, but I am not sure: https://github.com/satvshr/oppia-web-developer-docs/tree/satvshr

**Comment by satvshr** [comment]
> P.S. I suspect it might be because your remote repo is not up-to-date with develop, but I am not sure: https://github.com/satvshr/oppia-web-developer-docs/tree/satvshr

That was it.

**Review by seanlip — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
