### PR TITLE
Added docs for Hacktoberfest 2024

### PR DESCRIPTION
**Pull request by HardikGoyal2003**
This PR adds the documentation for participating in Hacktoberfest 2024.

### CODE REVIEW

**Comment by HardikGoyal2003** [comment]
@seanlip PTAL! Thanks!

**Review by seanlip — CHANGES_REQUESTED** [review]
Thanks -- you'll need to link to it in the sidebar too, right? You can add it below "Google Summer of Code 2024" in the top section and bold it.

**Comment by HardikGoyal2003** [comment]
@seanlip PTAL!! Thanks!!

**Review by seanlip — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
