### PR TITLE
Fix #156: Update Lace-Onboarding-Guide.md

### LINKED ISSUE #156: Update LaCE-onboarding-guide.md
The aim of this issue is to update the LaCE onboarding guide wiki page so that it can be used as a reference by new contributors who are working on LaCE issues. The specific things to do are:

1. Fix spelling errors noted in the review: https://github.com/oppia/oppia-web-developer-docs/pull/144/files
2. Add images/screenshots to illustrate key steps
3. Add an overview section (suggested by @Nik-09 in https://github.com/oppia/oppia-web-developer-docs/issues/28#issuecomment-1507114390)

### PR DESCRIPTION
**Pull request by prafulbbandre**
Fix #156

### CODE REVIEW

**Comment by prafulbbandre** [comment]
Hi @gp201 It's Ready.

**Review by gp201 — APPROVED** [review]
LGTM, Please get @SanjaySajuJacob approval before I can merge the PR.

**Comment by prafulbbandre** [comment]
Thanks @gp201

**Review by SanjaySajuJacob — APPROVED** [review]

**Comment by SanjaySajuJacob** [comment]
Hey @prafulbbandre , LGTM. @gp201 would you please merge this PR? Thanks!

**Pull request merged**
