### PR TITLE
Updates installation instructions for Linux

### PR DESCRIPTION
**Pull request by Patel-Muhammad**
This pull request updates the instructions for setting up the **`pyenv`** environment and makes it simpler to add the necessary lines to the **`.bashrc`** file by utilizing the echo command.

@U8NWXD, would you please review this pull request?

### CODE REVIEW

**Comment by Patel-Muhammad** [comment]
@seanlip can you please review this PR?

**Comment by seanlip** [comment]
This is a dev workflow change so I've assigned the dev workflow leads.

Personally I don't think this PR is needed / helps things, but let's see what they say.

**Comment by U8NWXD** [comment]
I agree with @seanlip. We expect contributors to be comfortable editing text files (they are writing code after all), so I think it's totally reasonable to ask them to add some lines to `~/.bashrc`.

Further, I think using `echo` actually makes the instructions more difficult to follow because readers can no longer copy the text that needs to be added to `~/.bashrc`, and it's harder to understand what the lines being added mean (e.g. we lose the bash syntax highlighting).

**Comment by U8NWXD** [comment]
I'm open to being convinced otherwise if you still disagree @Patel-Muhammad, but right now I don't think this is a change we want to make

**Comment by Patel-Muhammad** [comment]
Thank you for the update and for assigning the dev workflow leads. Looking forward to hear the feedback from the leads.

**Comment by U8NWXD** [comment]
Sorry, I should have made clear that I'm one of the dev workflow leads :)

**Comment by Patel-Muhammad** [comment]
@U8NWXD  I understand. Thank you for letting me know about your perspective, as a new contributor it will help my own perspective to get aligned with yours.

**Comment by Patel-Muhammad** [comment]
So, now should I close the pull request?

**Comment by seanlip** [comment]
Yes, since it's not needed. I'll do that.

**Pull request closed without merging**
