### PR TITLE
Add new release coordinators and remove wiki about model validations

### PR DESCRIPTION
**Pull request by vojtechjelinek**
- Add new release coordinators 
- Remove wiki about model validations as it is outdated and until we have a new system for writing validations we do not want to add them

Fixes oppia/oppia#17400

### CODE REVIEW

**Comment by vojtechjelinek** [comment]
@sagangwee @gp201 @chris7716 @SanjaySajuJacob @Priyansh61 Please check if you're fine with the assigned months. In that month you will be responsible for the release coordination, you will have some experienced coordinator at hand for any help. I will send more detailed instructions later.

@kevintab95 Can you check if you're fine being one of the contact persons for the release team?

**Review by gp201 — APPROVED** [review]
LGTM

**Comment by U8NWXD** [comment]
@sagangwee @kevintab95 @chris7716 @SanjaySajuJacob @Priyansh61 PTAL

**Review by kevintab95 — APPROVED** [review]

**Comment by kevintab95** [comment]
> @kevintab95 Can you check if you're fine being one of the contact persons for the release team?

Yup, thanks for checking! :)

**Review by Priyansh61 — APPROVED** [review]
LGTM!

**Review by chris7716 — APPROVED** [review]

**Review by sagangwee — APPROVED** [review]
LGTM.

**Comment by sagangwee** [comment]
@vojtechjelinek Sorry, is it possible to swap me for a different month than this upcoming March? I'm a bit swamped this week unfortunately.

**Comment by vojtechjelinek** [comment]
@sagangwee Done, swithced you to April, LMK if that is fine. @SanjaySajuJacob PTAL

**Review by SanjaySajuJacob — APPROVED** [review]

**Comment by vojtechjelinek** [comment]
@gp201 Please merge.

**Comment by vojtechjelinek** [comment]
@U8NWXD Please merge.

**Pull request merged**
