### PR TITLE
Table of Contents

### LINKED ISSUE #55: Add Table of contents for the troubleshooting page.
Currently the [troubleshooting page](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Troubleshooting.md) does not have a table do contents making hard for users to navigate the page.

### PR DESCRIPTION
**Pull request by deadex-ng**
This PR fixes #55 

I have added the Table of Contents to `Troubleshooting.md`

### CODE REVIEW

**Comment by gp201** [comment]
@deadex-ng Please remove the workflow from this PR. We will address that in PR #74

**Comment by deadex-ng** [comment]
@gp201 I've removed the workflow

**Comment by gp201** [comment]
@deadex-ng can you check if all the links work?

**Comment by deadex-ng** [comment]
> @deadex-ng can you check if all the links work?

@gp201 - Does this mean I have to add the link-checker workflow? Then if all the links work, I should remove the workflow?

**Comment by U8NWXD** [comment]
I just spot-checked the links and they look good to me

**Review by gp201 — APPROVED** [review]
LGTM

**Pull request merged**
